spring:
  cloud:
    stream:
      bindings:
        input:
          destination: topico-sddo-cotacao
        output:
          destination: topico-sddo-cotacao
      kafka:
        binder:
          auto-create-topics: true
          brokers: sb://eh-sddo-backend.servicebus.windows.net/
          configuration:
            sasl:
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required SharedAccessKeyName=QuotationAccessKey;SharedAccessKey=QC7XG4rhECdVr4NEwbiiHY/Bk+17K2XkY+AEhL/FE8w=;
              mechanism: PLAIN
            security:
              protocol: SASL_SSL

